version: '3'
services: 
  mysql:
    image: mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MY_SQL_USER: root
      MYSQL_ROOT_PASSWORD: null
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment: 
      - PMA_ARBITRARY=1
#  frontend:
#    build: ./frontend
#    restart: always
#    ports:
#      - 80:80
  backend:
    build: ./backend
    restart: always
    ports: 
      - 8001:80
    volumes:
      - ./backend/public_html:/var/www/html